### PR TITLE
[REPL] Test RPATH is set correctly on linux.

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/42863249>

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test and merge

**Comment by dcci** [comment]
@shahmishal / @aciidb0mb3r do we have CI of any kind on this bot? I tested my change extensively locally ,but I would feel better if swift-ci merged on my behalf :)

**Comment by shahmishal** [comment]
@dcci Unfortunately we don't have it yet.

**Comment by dcci** [comment]
Well, I guess I'll receive a mail in case this breaks anything.

**Comment by aciidb0mb3r** [comment]
Would be really awesome to get the CI support on this repo!

**Comment by shahmishal** [comment]
@dcci Can you update the README with the test info? Thanks!

**Comment by dcci** [comment]
My bad, as @gottesmm pointed out, this should go in an already existing directory. I'll move it.

**Pull request merged**
