### PR TITLE
[py3] Ensure we are using text streams

### PR DESCRIPTION
**Pull request by edymtt**
This is needed since now we invoking `lit.py` with python3

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by edymtt** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
16:53:56     p = subprocess.Popen(skargs, stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)
16:53:56 TypeError: __init__() got an unexpected keyword argument 'text'
```

**Comment by edymtt** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
17:13:44 Failed Tests (2):
17:13:44   swift-package-tests :: test-snapshot-binaries/linux_load_commands.py
17:13:44   swift-package-tests :: test-snapshot-binaries/test-rpath-linux.py
```

**Comment by shahmishal** [comment]
Going to merge this for now, this does not look related to python3 issue.

**Pull request merged**
